<?php
$statusMsg = false;

if ($app->auth()->checkLogin()) {
    header('Location: ' . $app->utils()->getPanelURL() . 'app');
}


if ($_GET['handler'] == "forgot-password") {

    $form = [
        'status' => null,
        'email' => trim($_POST['email'])
    ];

    $userID = $app->auth()->getUserID($form['email'])['data']['userID'];

    if (!isset($userID) || empty($userID)) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['usernotexist']."</div>";
    }



    if (!$error && (strtotime($app->auth()->getUser($userID)->getPasswordCodeTime())+$app->utils()->getSetting('panel_passwordRequestDelay')) > time()) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-info\" role=\"alert\">".str_replace('{MINUTES}', $app->utils()->convertTime($app->utils()->getSetting('panel_passwordRequestDelay'))['min'], $lng['error']['forgetpassword_delay'])."</div>";
    }

    if (!$error) {
        $pwCode = $app->auth()->getUser($userID)->createPasswordCode();
        $data = [
            'username' => $app->auth()->getUser($userID)->getUsername(),
            'resetLink' => $app->utils()->getPanelURL() . 'forgot-password/' . $pwCode,
            'app' => $app
        ];
        if ($app->utils()->phpMailerSMTP($app->auth()->getUser($userID)->getEmail(), $lng['forgot_password']['title'].' | '.$app->utils()->getSetting('panel_title'), getIncludeContent("_storage/static/mail/html/forgot_password.ctp", $data))) {
            $statusMsg = true;
            $form['status'] = "<div class=\"alert alert-success\" role=\"alert\">".$lng['success']['linksent']."</div>";
        } else {
            $app->auth()->getUser($userID)->deletePasswordCode();
            $statusMsg = true;
            $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['internalerror']."</div>";
        }

    }


}