<?php
use Klefiu\App\Config;
$statusMsg = false;

if ($app->auth()->checkLogin()) {
    header('Location: ' . $app->utils()->getPanelURL() . 'app');
}

if ($_GET['handler'] == "reset-password") {

    $error = null;
    $form = [
        'status' => null,
        'resetToken' => $_POST['resetToken'],
        'newPassword' => $_POST['newPassword'],
        'newPassword2' => $_POST['newPassword2']
    ];

    $statement = $app->sql()->getPDO()->prepare("SELECT * FROM " . Config::read('db_prefix') . "users WHERE pwCode = ?");
    $result = $statement->execute([sha1($form['resetToken'])]);
    $userData = $statement->fetch();

    if (is_null($userData)) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['invalidtoken']."</div>";
    } elseif ((strtotime($userData['pwCode_time']) + 3600) < time()) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['invalidtoken']."</div>";
    }

    if (!$error && (empty($form['newPassword']) || empty($form['newPassword2']))) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['emptystring']."</div>";
    }

    if (!$error && $form['newPassword'] !== $form['newPassword2']) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['passwordmatch']."</div>";
    }

    if (!$error && password_verify($form['newPassword'], $app->auth()->getUser($userData['ID'])->getPasswordHash())) {
        $error = true;
        $statusMsg = true;
        $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['nopasswordchange']."</div>";
    }

    if (!$error) {
        if ($app->auth()->getUser($userData['ID'])->setData('password', password_hash($form['newPassword'], PASSWORD_DEFAULT))) {
            $app->auth()->getUser($userData['ID'])->deletePasswordCode();
            $data = [
                'username' => $app->auth()->getUser($userData['ID'])->getUsername(),
                'app' => $app
            ];
            $app->utils()->phpMailerSMTP($app->auth()->getUser($userData['ID'])->getEmail(), $lng['email']['passwordupdate'].' | '.$app->utils()->getSetting('panel_title'), getIncludeContent("_storage/static/mail/html/password_change.ctp", $data));
            header('Location: ' . $app->utils()->getPanelURL() . 'login?action=passwordResetted');
        } else {
            $error = true;
            $statusMsg = true;
            $form['status'] = "<div class=\"alert alert-danger\" role=\"alert\">".$lng['error']['internalerror']."</div>";
        }
    }



}

